runtime: nodejs20
service: fe

handlers:
  - url: /static
    static_dir: static

  - url: /
    static_files: index.html
    upload: index.html

  - url: /index.html
    static_files: index.html
    upload: index.html

  - url: /script.js
    static_files: script.js
    upload: script.js

  - url: /style.css
    static_files: style.css
    upload: style.css

  - url: /pastNote.html
    static_files: pastNote.html
    upload: pastNote.html

  - url: /add-note.html
    static_files: add-note.html
    upload: add-note.html

  - url: /edit-note.html
    static_files: edit-note.html
    upload: edit-note.html
  
  - url: /edit-profile.html
    static_files: edit-profile.html
    upload: edit-profile.html
  
  - url: /login.html
    static_files: login.html
    upload: login.html
  
  - url: /register.html
    static_files: register.html
    upload: register.html
  
  - url: /auth.js
    static_files: auth.js
    upload: auth.js

  - url: /config.js
    static_files: config.js
    upload: config.js

  - url: /account.js
    static_files: account.js
    upload: account.js
  
